# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainmenu.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainMenu(object):
    def setupUi(self, MainMenu):
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(659, 508)
        self.centralwidget = QtWidgets.QWidget(MainMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add.setGeometry(QtCore.QRect(240, 10, 171, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setStyleSheet("color: rgb(33, 152, 175);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Docs/Ubuntu_Studio-icon-pd2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_add.setIcon(icon)
        self.pushButton_add.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_add.setFlat(True)
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_modify = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_modify.setGeometry(QtCore.QRect(260, 100, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_modify.setFont(font)
        self.pushButton_modify.setStyleSheet("color: rgb(33, 152, 175);")
        self.pushButton_modify.setIcon(icon)
        self.pushButton_modify.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_modify.setFlat(True)
        self.pushButton_modify.setObjectName("pushButton_modify")
        self.pushButton_search = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_search.setGeometry(QtCore.QRect(260, 180, 191, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_search.setFont(font)
        self.pushButton_search.setStyleSheet("color: rgb(33, 152, 175);")
        self.pushButton_search.setIcon(icon)
        self.pushButton_search.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_search.setFlat(True)
        self.pushButton_search.setObjectName("pushButton_search")
        self.pushButton_display = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_display.setGeometry(QtCore.QRect(260, 270, 201, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_display.setFont(font)
        self.pushButton_display.setStyleSheet("color: rgb(33, 152, 175);")
        self.pushButton_display.setIcon(icon)
        self.pushButton_display.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_display.setFlat(True)
        self.pushButton_display.setObjectName("pushButton_display")
        self.pushButton_about = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_about.setGeometry(QtCore.QRect(270, 350, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_about.setFont(font)
        self.pushButton_about.setStyleSheet("color: rgb(33, 152, 175);")
        self.pushButton_about.setIcon(icon)
        self.pushButton_about.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_about.setFlat(True)
        self.pushButton_about.setObjectName("pushButton_about")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(260, 430, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("color: rgb(33, 152, 175);")
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 661, 511))
        self.widget.setStyleSheet("background-image: url(\"C:/Users/Dustin/Documents/School/CSULA/CS 437/VDATABASE/Docs/background.jpg\");")
        self.widget.setObjectName("widget")
        self.label_date = QtWidgets.QLabel(self.widget)
        self.label_date.setGeometry(QtCore.QRect(10, 10, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_date.setFont(font)
        self.label_date.setStyleSheet("color: rgb(1, 170, 216);")
        self.label_date.setObjectName("label_date")
        self.widget.raise_()
        self.pushButton_add.raise_()
        self.pushButton_modify.raise_()
        self.pushButton_search.raise_()
        self.pushButton_display.raise_()
        self.pushButton_about.raise_()
        self.pushButton_6.raise_()
        MainMenu.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainMenu)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)

    def retranslateUi(self, MainMenu):
        _translate = QtCore.QCoreApplication.translate
        MainMenu.setWindowTitle(_translate("MainMenu", "MainWindow"))
        self.pushButton_add.setText(_translate("MainMenu", "ADD"))
        self.pushButton_modify.setText(_translate("MainMenu", "MODIFY"))
        self.pushButton_search.setText(_translate("MainMenu", "SEARCH"))
        self.pushButton_display.setText(_translate("MainMenu", "DISPLAY"))
        self.pushButton_about.setText(_translate("MainMenu", "ABOUT"))
        self.pushButton_6.setText(_translate("MainMenu", "EXIT"))
        self.label_date.setText(_translate("MainMenu", "<html><head/><body><p><span style=\" font-weight:400; color:#ffffff;\">TextLabel</span></p></body></html>"))

